Formula parser & alias cleanup & rich-based help
caracal-pipeline/scabha2 pull request #21
Opened 2022-03-31 09:42 UTC by o-smirnov

Sorry @SpheMakh, this is a big gulp. I know I keep beating the drum for small feature branches, but since you're ignoring my PRs, they just snowball into major ones.

2022-04-04 11:23 UTC, SpheMakh requested changes
very minor changes

2022-04-04 11:23 UTC, SpheMakh commented on scabha/types.py
> +import os.path
![elmo](https://media.giphy.com/media/1CRLn4g4MiIyA/giphy.gif)

2022-04-04 11:23 UTC, SpheMakh commented on tests/test_parsing.py
> +    test_parser()
add new line at end

2022-04-05 08:57 UTC, o-smirnov commented
OK @SpheMakh please approve and merge.

2022-04-05 09:43 UTC, merged